"""Generate matvec kernels with the 24x24 element stiffness inlined as literals (no Ke loads).

Writes genk_warp.py (Warp kernels mv_fp32 / mv_fp64) and genk_numba.py (Numba functions
mv_fp32 / mv_fp64). Same node-based gather as bench_matvec.py: one thread per node, its 3 rows,
summed over up to 8 incident elements; per element, 24 x-loads and 3 dot products of length 24.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from bench_matvec import CORNERS, KE

HERE = Path(__file__).resolve().parent


def body(lit, zero, ind="    "):
    L = []
    L.append(f"{ind}m = n + 1")
    L.append(f"{ind}ix = i // (m * m)")
    L.append(f"{ind}iy = (i // m) % m")
    L.append(f"{ind}iz = i % m")
    L.append(f"{ind}a0 = {zero}")
    L.append(f"{ind}a1 = {zero}")
    L.append(f"{ind}a2 = {zero}")
    for a in range(8):
        ca = CORNERS[a]
        L.append(f"{ind}ex = ix - {ca[0]}")
        L.append(f"{ind}ey = iy - {ca[1]}")
        L.append(f"{ind}ez = iz - {ca[2]}")
        L.append(f"{ind}if ex >= 0 and ex < n and ey >= 0 and ey < n and ez >= 0 and ez < n:")
        j = ind + "    "
        L.append(f"{j}r = rho[(ex * n + ey) * n + ez]")
        for b in range(8):
            cb = CORNERS[b]
            L.append(f"{j}q{b} = 3 * (((ex + {cb[0]}) * m + (ey + {cb[1]})) * m + (ez + {cb[2]}))")
            for d in range(3):
                L.append(f"{j}x{3 * b + d} = x[q{b} + {d}]")
        for c in range(3):
            row = KE[3 * a + c]
            terms = [f"{lit(row[k])} * x{k}" for k in range(24) if row[k] != 0.0]
            L.append(f"{j}s{c} = " + " + ".join(terms))
        L.append(f"{j}a0 = a0 + r * s0")
        L.append(f"{j}a1 = a1 + r * s1")
        L.append(f"{j}a2 = a2 + r * s2")
    L.append(f"{ind}y[3 * i] = a0")
    L.append(f"{ind}y[3 * i + 1] = a1")
    L.append(f"{ind}y[3 * i + 2] = a2")
    return "\n".join(L)


def main():
    w = ["# generated by gen_kernels.py — do not edit", "import warp as wp", ""]
    for name, wt in (("fp32", "wp.float32"), ("fp64", "wp.float64")):
        lit = (lambda v: repr(float(v))) if name == "fp32" else (lambda v: f"wp.float64({float(v)!r})")
        w.append("@wp.kernel")
        w.append(f"def mv_{name}(n: int, rho: wp.array(dtype={wt}), x: wp.array(dtype={wt}), y: wp.array(dtype={wt})):")
        w.append("    i = wp.tid()")
        w.append(body(lit, f"{wt}(0.0)"))
        w.append("")
    (HERE / "genk_warp.py").write_text("\n".join(w) + "\n", encoding="utf-8")

    nbm = ["# generated by gen_kernels.py — do not edit", "import numba as nb", "import numpy as np", ""]
    for name, npt in (("fp32", "np.float32"), ("fp64", "np.float64")):
        nbm.append(f"F_{name} = {npt}")
        nbm.append("@nb.njit(parallel=True, fastmath=True)")
        nbm.append(f"def mv_{name}(n, rho, x, y):")
        nbm.append("    for i in nb.prange((n + 1) ** 3):")
        nbm.append(body(lambda v, t=npt: f"{t}({float(v)!r})", f"{npt}(0.0)", ind="        "))
        nbm.append("")
    (HERE / "genk_numba.py").write_text("\n".join(nbm) + "\n", encoding="utf-8")
    print("generated", len(w), "warp lines,", len(nbm), "numba lines")


if __name__ == "__main__":
    main()
