"""Slice evidence for a coupon plate: what the slicer generated per rung (tier S), schema fdmgen/slice-evidence@0.1.

Pairs the plate's rung metadata (fdmgen/coupon-plate@0.1, print frame, mm) with the real G-code:
support roads under each rung, and for bridge rungs the bridge roads on the first deck layer. It
records the slicer settings that decide support and bridging, so the evidence is never read without
the conditions it was produced under. It establishes what Orca generates, never how the plate prints.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

import numpy as np

from ..catalog.checks.proc import settings_from_gcode
from ..catalog.checks.toolpath import locate, support_by_region
from ..gcode import extruder_offset, read_gcode

SCHEMA = "fdmgen/slice-evidence@0.1"
KEYS = ("enable_support", "support_threshold_angle", "support_type", "bridge_no_support", "support_on_build_plate_only",
        "layer_height", "wall_loops", "filament_type", "filament_settings_id", "print_settings_id", "printer_model",
        "filament_shrink", "extruder_offset", "enable_arc_fitting", "thick_bridges", "bridge_angle")


def slice_evidence(plate: dict, gcode_path, plate_name: str = "", plate_sha256: str = "") -> dict:
    raw = Path(gcode_path).read_bytes()
    text = raw.decode("utf-8")
    tp = read_gcode(text)
    off = extruder_offset(text)
    cfg = settings_from_gcode(text)
    gen = re.search(r"^; generated by (\S+) (\S+)", text, re.MULTILINE)
    rungs = plate["rungs"]
    lo = np.min([r["bbox_mm"][0] for r in rungs], axis=0)
    hi = np.max([r["bbox_mm"][1] for r in rungs], axis=0)
    shift = locate(tp, lo[:2], hi[:2], off)
    regions = {}
    for r in rungs:
        if r["kind"] == "overhang":                          # footprint under the sloped face
            (x0, y0, _), (x1, y1, _) = r["bbox_mm"]
            regions[r["id"]] = ([x1 - (x1 - x0 - r.get("base_mm", 6.0)), y0], [x1, y1])
        else:
            regions[r["id"]] = (r["bridge_bbox_mm"][0][:2], r["bridge_bbox_mm"][1][:2])
    sup = support_by_region(tp, regions, shift, off)
    low = np.char.lower(tp.role.astype(str))
    mid = (tp.start + tp.end) / 2
    xy = mid[:, :2] + off[:2] - shift
    seg_len = np.linalg.norm(tp.end - tp.start, axis=1)
    out_rungs = []
    for r in rungs:
        row = {"id": r["id"], "kind": r["kind"], **{k: r[k] for k in ("alpha_deg", "span_mm") if k in r},
               **{k: v for k, v in sup[r["id"]].items()}}
        if r["kind"] == "bridge":
            (bx0, by0, z0), (bx1, by1, _) = r["bridge_bbox_mm"]
            first = np.abs(mid[:, 2] - (z0 + float(cfg.get("layer_height", 0.2)))) < 0.11
            inb = first & (xy[:, 0] >= bx0) & (xy[:, 0] <= bx1) & (xy[:, 1] >= by0 - 0.5) & (xy[:, 1] <= by1 + 0.5)
            br = inb & (np.char.find(low, "bridge") >= 0)
            row["bridge_roads_first_deck_layer"] = int(br.sum())
            row["longest_bridge_road_mm"] = float(seg_len[br].max()) if br.any() else 0.0
        out_rungs.append(row)
    return {
        "schema": SCHEMA, "tier": "S",
        "plate": {"name": plate_name, "sha256": plate_sha256, "schema": plate.get("schema")},
        "gcode": {"sha256": hashlib.sha256(raw).hexdigest(), "generator": gen.group(1) if gen else None,
                  "version": gen.group(2) if gen else None, "settings": {k: cfg.get(k) for k in KEYS}},
        "placement": {"shift_xy_mm": np.round(shift, 4).tolist(), "extruder_offset_mm": off.tolist()},
        "rungs": out_rungs,
        "unassigned_support_segments": sup["_unassigned"]["support_segments"],
        "establishes": "What the slicer generated for each rung under the recorded settings (support roads, bridge roads).",
        "does_not_establish": "How the rungs print on the printer (P level): sag, curl, droop and bridge quality need the printed plate.",
    }
