"""P0-B on a real part: Orca slices of one project with and without arc fitting, read by the canonical reader.

Compares credited volume (total and per role) against the slicer's own footers, and the deposited material
on one shared print-frame grid. The receipt names inputs by sha256 only, never by path.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

import numpy as np

from fdmgen.gcode import credit, extruder_offset, read_gcode
from fdmgen.gcode.occupancy import deposit

TIE_BREAK_MM = 1e-4 * np.pi          # same reason as the shell check: no sample sits exactly on a cell edge


def load(path: Path) -> dict:
    raw = path.read_bytes()
    text = raw.decode("utf-8")
    tp = read_gcode(text)                                  # footer guard on
    gen = re.search(r"^; generated by (\S+) (\S+)", text, re.MULTILINE)
    arc_cfg = re.search(r"^; enable_arc_fitting = (\S+)", text, re.MULTILINE)
    footer = float(re.search(r"^; filament used \[mm\] = ([0-9.]+)", text, re.MULTILINE).group(1))
    return {"tp": tp, "offset": np.asarray(extruder_offset(text), float), "sha256": hashlib.sha256(raw).hexdigest(),
            "generator": f"{gen.group(1)} {gen.group(2)}" if gen else None,
            "enable_arc_fitting": arc_cfg.group(1) if arc_cfg else None, "footer_filament_mm": footer}


def summary(s: dict) -> dict:
    tp = s["tp"]
    cr = credit(tp)
    m = cr["credited_mask"]
    roles = sorted(set(tp.role[m].astype(str)))
    return {"gcode_sha256": s["sha256"], "generator": s["generator"], "enable_arc_fitting": s["enable_arc_fitting"],
            "arc_chords_in_object": int(tp.from_arc[tp.in_object].sum()),
            "footer_filament_mm": s["footer_filament_mm"],
            "credited_mm3": cr["structurally_credited_extrusion_volume_mm3"],
            "credited_by_role_mm3": {r: float(tp.volume[m & (tp.role == r)].sum()) for r in roles}}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("plain", type=Path, help="slice with enable_arc_fitting = 0")
    ap.add_argument("arced", type=Path, help="slice of the same project with enable_arc_fitting = 1")
    ap.add_argument("--project-sha256", nargs=2, metavar=("PLAIN", "ARCED"), required=True,
                    help="sha256 of the two sliced projects (recorded, not checked)")
    ap.add_argument("--cell", type=float, default=0.4)
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()
    p, q = load(a.plain), load(a.arced)
    sp, sq = summary(p), summary(q)
    if sp["enable_arc_fitting"] != "0" or sq["enable_arc_fitting"] != "1":
        ap.error("the first slice must have arc fitting off and the second on")

    ends = np.vstack([p["tp"].start + p["offset"], p["tp"].end + p["offset"]])[np.tile(p["tp"].in_object, 2)]
    origin = ends.min(axis=0) - 1.0 + TIE_BREAK_MM
    shape = tuple(int(x) for x in np.ceil((ends.max(axis=0) + 1.0 - origin) / a.cell))
    grids = []
    for s in (p, q):
        g, out = deposit(s["tp"], s["offset"], np.eye(3), np.zeros(3), origin, a.cell, shape)
        grids.append((g, out))
    (g0, o0), (g1, o1) = grids
    cell_v = a.cell ** 3
    d0, d1 = g0 / cell_v, g1 / cell_v
    rel = (sq["credited_mm3"] - sp["credited_mm3"]) / sp["credited_mm3"]
    roles = sorted(set(sp["credited_by_role_mm3"]) | set(sq["credited_by_role_mm3"]))
    receipt = {
        "schema": "fdmgen-bench/arc-parity@0.1",
        "projects_sha256": {"plain": a.project_sha256[0], "arced": a.project_sha256[1]},
        "plain": sp, "arced": sq,
        "credited_relative_difference": rel,
        "footer_relative_difference": (sq["footer_filament_mm"] - sp["footer_filament_mm"]) / sp["footer_filament_mm"],
        "role_relative_difference": {r: (sq["credited_by_role_mm3"].get(r, 0.0) - sp["credited_by_role_mm3"].get(r, 0.0))
                                     / max(sp["credited_by_role_mm3"].get(r, 0.0), 1e-12) for r in roles},
        "grid": {"frame": "print (plate) frame, extruder offset restored", "cell_mm": a.cell, "shape": list(shape),
                 "origin_mm": origin.tolist(), "caps": False, "step_frac": "1/3",
                 "clipped_mm3": {"plain": o0, "arced": o1}},
        "occupancy": {"moved_fraction": float(np.abs(g1 - g0).sum() / 2 / g0.sum()),
                      "max_abs_cell_density_change": float(np.abs(d1 - d0).max()),
                      "solid_mask_flips_at_0p5": int(((d0 >= 0.5) != (d1 >= 0.5)).sum()),
                      "solid_cells": {"plain": int((d0 >= 0.5).sum()), "arced": int((d1 >= 0.5).sum())}},
        "gate": {"P0-B": "credited volume within 0.1 % (relative)", "met": bool(abs(rel) < 1e-3)},
        "establishes": "That the reader credits the same material, and places it in the same cells, whether Orca "
                       "writes this part's curves as arcs or as chords.",
        "does_not_establish": "Equality for every part (arc fitting changes Orca's own plan, visible as the footer "
                              "difference), or anything about the printed result.",
    }
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(receipt, indent=1) + "\n", encoding="utf-8")
    print(f"credited {sp['credited_mm3']:.3f} vs {sq['credited_mm3']:.3f} mm3 ({100 * rel:+.4f} %), footer "
          f"{100 * receipt['footer_relative_difference']:+.4f} %, moved {100 * receipt['occupancy']['moved_fraction']:.3f} %, "
          f"P0-B {'met' if receipt['gate']['met'] else 'NOT met'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
