"""Matrix-free structured-grid elasticity on NVIDIA GPUs (Warp).

Operator kernels are code-generated with the 24x24 element stiffness inlined as literals (no
stiffness loads; measured faster than the spool-rack gpu_hex operator, research/checks/bench).
Node-based gather: one thread per node computes its 3 rows over up to 8 incident elements, so
there are no atomics. Grid/DOF numbering as in reference.py. Fixed DOFs act as identity rows;
all solver vectors are kept zero at fixed DOFs, so the gather needs no column masking.
"""

import hashlib
import importlib.util
import os
from pathlib import Path

import numpy as np
import warp as wp

from .element import CORNERS

wp.config.quiet = True
CACHE = Path(os.environ.get("FDMGEN_CACHE", Path(__file__).resolve().parents[3] / ".cache")) / "kernels"


def _lit(v: float, dt: str) -> str:
    return repr(float(v)) if dt == "float32" else f"wp.float64({float(v)!r})"


def _gather_body(Ke: np.ndarray, dt: str, diag_only: bool) -> list[str]:
    W = f"wp.{dt}"
    L = [
        "    i = wp.tid()",
        "    mx = nx + 1",
        "    my = ny + 1",
        "    mz = nz + 1",
        "    ix = i // (my * mz)",
        "    iy = (i // mz) % my",
        "    iz = i % mz",
        f"    a0 = {W}(0.0)",
        f"    a1 = {W}(0.0)",
        f"    a2 = {W}(0.0)",
    ]
    for a in range(8):
        ca = CORNERS[a]
        L += [f"    ex = ix - {ca[0]}", f"    ey = iy - {ca[1]}", f"    ez = iz - {ca[2]}",
              "    if ex >= 0 and ex < nx and ey >= 0 and ey < ny and ez >= 0 and ez < nz:",
              "        r = E[(ex * ny + ey) * nz + ez]"]
        if diag_only:
            for c in range(3):
                L.append(f"        a{c} = a{c} + r * {_lit(Ke[3 * a + c, 3 * a + c], dt)}")
            continue
        for b in range(8):
            cb = CORNERS[b]
            L.append(f"        q{b} = 3 * (((ex + {cb[0]}) * my + (ey + {cb[1]})) * mz + (ez + {cb[2]}))")
            for d in range(3):
                L.append(f"        x{3 * b + d} = x[q{b} + {d}]")
        for c in range(3):
            row = Ke[3 * a + c]
            terms = [f"{_lit(row[k], dt)} * x{k}" for k in range(24) if row[k] != 0.0]
            L.append(f"        s{c} = " + " + ".join(terms))
            L.append(f"        a{c} = a{c} + r * s{c}")
    return L


def _module_source(Ke: np.ndarray) -> str:
    src = ["# generated by fdmgen.fem.warp_structured: do not edit", "import warp as wp", ""]
    for dt in ("float32", "float64"):
        W = f"wp.{dt}"
        src += ["@wp.kernel",
                f"def matvec_{dt}(nx: int, ny: int, nz: int, scale: {W}, E: wp.array(dtype={W}),",
                f"               fixed: wp.array(dtype=wp.int32), x: wp.array(dtype={W}), y: wp.array(dtype={W})):"]
        src += _gather_body(Ke, dt, False)
        src += ["    for c in range(3):",
                "        k = 3 * i + c",
                "        if fixed[k] != 0:",
                "            y[k] = x[k]",
                "        else:",
                "            if c == 0:",
                "                y[k] = scale * a0",
                "            elif c == 1:",
                "                y[k] = scale * a1",
                "            else:",
                "                y[k] = scale * a2",
                "",
                "@wp.kernel",
                f"def diag_{dt}(nx: int, ny: int, nz: int, scale: {W}, E: wp.array(dtype={W}),",
                f"             fixed: wp.array(dtype=wp.int32), d: wp.array(dtype={W})):"]
        src += _gather_body(Ke, dt, True)
        src += ["    for c in range(3):",
                "        k = 3 * i + c",
                "        if fixed[k] != 0:",
                f"            d[k] = {W}(1.0)",
                "        else:",
                "            if c == 0:",
                "                d[k] = scale * a0",
                "            elif c == 1:",
                "                d[k] = scale * a1",
                "            else:",
                "                d[k] = scale * a2",
                ""]
    return "\n".join(src) + "\n"


_LOADED: dict[str, object] = {}


def operator_module(Ke: np.ndarray):
    """Import (generating if needed) the kernel module for this element stiffness."""
    key = hashlib.sha256(np.ascontiguousarray(Ke, dtype=np.float64).tobytes()).hexdigest()[:16]
    if key in _LOADED:
        return _LOADED[key]
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"ke_{key}.py"
    if not path.exists():
        tmp = path.with_suffix(".tmp")
        tmp.write_text(_module_source(Ke), encoding="utf-8")
        os.replace(tmp, path)
    spec = importlib.util.spec_from_file_location(f"fdmgen_ke_{key}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    _LOADED[key] = mod
    return mod


# ── precision-generic helpers ───────────────────────────────────────────────────

def _helpers(dt):
    @wp.kernel
    def axpby(a: dt, x: wp.array(dtype=dt), b: dt, y: wp.array(dtype=dt), out: wp.array(dtype=dt)):
        i = wp.tid()
        out[i] = a * x[i] + b * y[i]

    @wp.kernel
    def mul(d: wp.array(dtype=dt), x: wp.array(dtype=dt), out: wp.array(dtype=dt)):
        i = wp.tid()
        out[i] = d[i] * x[i]

    @wp.kernel
    def inv(d: wp.array(dtype=dt), out: wp.array(dtype=dt)):
        i = wp.tid()
        out[i] = dt(1.0) / d[i]

    @wp.kernel
    def mask(fixed: wp.array(dtype=wp.int32), x: wp.array(dtype=dt)):
        i = wp.tid()
        if fixed[i] != 0:
            x[i] = dt(0.0)

    @wp.kernel
    def prolong_add(nxc: int, nyc: int, nzc: int, xc: wp.array(dtype=dt), xf: wp.array(dtype=dt)):
        # fine node (i, j, k); coarse node I contributes with weight 1 if i == 2I, 0.5 if |i - 2I| == 1
        t = wp.tid()
        myf = 2 * nyc + 1
        mzf = 2 * nzc + 1
        i = t // (myf * mzf)
        j = (t // mzf) % myf
        k = t % mzf
        myc = nyc + 1
        mzc = nzc + 1
        s0 = dt(0.0)
        s1 = dt(0.0)
        s2 = dt(0.0)
        for di in range(2):
            I = i // 2 + di
            wi = dt(1.0)
            if i % 2 == 0:
                if di == 1:
                    wi = dt(0.0)
            else:
                wi = dt(0.5)
            if wi != dt(0.0) and I <= nxc:
                for dj in range(2):
                    J = j // 2 + dj
                    wj = dt(1.0)
                    if j % 2 == 0:
                        if dj == 1:
                            wj = dt(0.0)
                    else:
                        wj = dt(0.5)
                    if wj != dt(0.0) and J <= nyc:
                        for dk in range(2):
                            K = k // 2 + dk
                            wk = dt(1.0)
                            if k % 2 == 0:
                                if dk == 1:
                                    wk = dt(0.0)
                            else:
                                wk = dt(0.5)
                            if wk != dt(0.0) and K <= nzc:
                                w = wi * wj * wk
                                q = 3 * ((I * myc + J) * mzc + K)
                                s0 = s0 + w * xc[q]
                                s1 = s1 + w * xc[q + 1]
                                s2 = s2 + w * xc[q + 2]
        xf[3 * t] = xf[3 * t] + s0
        xf[3 * t + 1] = xf[3 * t + 1] + s1
        xf[3 * t + 2] = xf[3 * t + 2] + s2

    @wp.kernel
    def restrict(nxc: int, nyc: int, nzc: int, rf: wp.array(dtype=dt), rc: wp.array(dtype=dt)):
        # transpose of prolong_add: coarse node I gathers fine nodes 2I-1..2I+1 per axis
        t = wp.tid()
        myc = nyc + 1
        mzc = nzc + 1
        I = t // (myc * mzc)
        J = (t // mzc) % myc
        K = t % mzc
        mxf = 2 * nxc + 1
        myf = 2 * nyc + 1
        mzf = 2 * nzc + 1
        s0 = dt(0.0)
        s1 = dt(0.0)
        s2 = dt(0.0)
        for di in range(3):
            i = 2 * I - 1 + di
            if i >= 0 and i < mxf:
                wi = dt(0.5)
                if di == 1:
                    wi = dt(1.0)
                for dj in range(3):
                    j = 2 * J - 1 + dj
                    if j >= 0 and j < myf:
                        wj = dt(0.5)
                        if dj == 1:
                            wj = dt(1.0)
                        for dk in range(3):
                            k = 2 * K - 1 + dk
                            if k >= 0 and k < mzf:
                                wk = dt(0.5)
                                if dk == 1:
                                    wk = dt(1.0)
                                w = wi * wj * wk
                                q = 3 * ((i * myf + j) * mzf + k)
                                s0 = s0 + w * rf[q]
                                s1 = s1 + w * rf[q + 1]
                                s2 = s2 + w * rf[q + 2]
        rc[3 * t] = s0
        rc[3 * t + 1] = s1
        rc[3 * t + 2] = s2

    @wp.kernel
    def coarsen_E(nxc: int, nyc: int, nzc: int, Ef: wp.array(dtype=dt), Ec: wp.array(dtype=dt)):
        e = wp.tid()
        ex = e // (nyc * nzc)
        ey = (e // nzc) % nyc
        ez = e % nzc
        nyf = 2 * nyc
        nzf = 2 * nzc
        s = dt(0.0)
        for a in range(2):
            for b in range(2):
                for c in range(2):
                    s = s + Ef[((2 * ex + a) * nyf + (2 * ey + b)) * nzf + (2 * ez + c)]
        Ec[e] = s * dt(0.125)

    return {"axpby": axpby, "mul": mul, "inv": inv, "mask": mask, "prolong_add": prolong_add,
            "restrict": restrict, "coarsen_E": coarsen_E}


@wp.kernel
def cast_32_64(x: wp.array(dtype=wp.float32), y: wp.array(dtype=wp.float64)):
    i = wp.tid()
    y[i] = wp.float64(x[i])


@wp.kernel
def cast_64_32(x: wp.array(dtype=wp.float64), y: wp.array(dtype=wp.float32)):
    i = wp.tid()
    y[i] = wp.float32(x[i])


@wp.kernel
def dot_partial_64(x: wp.array(dtype=wp.float64), y: wp.array(dtype=wp.float64), n: int,
                   out: wp.array(dtype=wp.float64)):
    # each thread sums a strided chunk, then one atomic per thread block of work
    t = wp.tid()
    s = wp.float64(0.0)
    stride = wp.int32(65536)
    i = t
    while i < n:
        s = s + x[i] * y[i]
        i = i + stride
    wp.atomic_add(out, 0, s)


HELPERS = {np.float32: _helpers(wp.float32), np.float64: _helpers(wp.float64)}


def dot64(x, y, buf):
    buf.zero_()
    wp.launch(dot_partial_64, dim=65536, inputs=[x, y, x.shape[0], buf], device=x.device)
    return float(buf.numpy()[0])


# ── coarse levels with explicit (Galerkin) element matrices ─────────────────────

@wp.kernel
def matvec_elem_f32(nx: int, ny: int, nz: int, Kel: wp.array(dtype=wp.float32), fixed: wp.array(dtype=wp.int32),
                    x: wp.array(dtype=wp.float32), y: wp.array(dtype=wp.float32)):
    """y = sum_e Kel[e] x_e (per-element 24x24, row-major, DOF 3a+c), node gather, identity at fixed."""
    i = wp.tid()
    mx = nx + 1
    my = ny + 1
    mz = nz + 1
    ix = i // (my * mz)
    iy = (i // mz) % my
    iz = i % mz
    a0 = float(0.0)
    a1 = float(0.0)
    a2 = float(0.0)
    for a in range(8):
        cx = a % 2
        cy = (a // 2) % 2
        cz = a // 4
        ex = ix - cx
        ey = iy - cy
        ez = iz - cz
        if ex >= 0 and ex < nx and ey >= 0 and ey < ny and ez >= 0 and ez < nz:
            base = ((ex * ny + ey) * nz + ez) * 576
            for b in range(8):
                bx = b % 2
                by = (b // 2) % 2
                bz = b // 4
                q = 3 * (((ex + bx) * my + (ey + by)) * mz + (ez + bz))
                for d in range(3):
                    xv = x[q + d]
                    col = 3 * b + d
                    a0 = a0 + Kel[base + (3 * a) * 24 + col] * xv
                    a1 = a1 + Kel[base + (3 * a + 1) * 24 + col] * xv
                    a2 = a2 + Kel[base + (3 * a + 2) * 24 + col] * xv
    for c in range(3):
        k = 3 * i + c
        if fixed[k] != 0:
            y[k] = x[k]
        else:
            if c == 0:
                y[k] = a0
            elif c == 1:
                y[k] = a1
            else:
                y[k] = a2


@wp.kernel
def diag_elem_f32(nx: int, ny: int, nz: int, Kel: wp.array(dtype=wp.float32), fixed: wp.array(dtype=wp.int32),
                  d: wp.array(dtype=wp.float32)):
    i = wp.tid()
    my = ny + 1
    mz = nz + 1
    ix = i // (my * mz)
    iy = (i // mz) % my
    iz = i % mz
    a0 = float(0.0)
    a1 = float(0.0)
    a2 = float(0.0)
    for a in range(8):
        ex = ix - a % 2
        ey = iy - (a // 2) % 2
        ez = iz - a // 4
        if ex >= 0 and ex < nx and ey >= 0 and ey < ny and ez >= 0 and ez < nz:
            base = ((ex * ny + ey) * nz + ez) * 576
            a0 = a0 + Kel[base + (3 * a) * 24 + 3 * a]
            a1 = a1 + Kel[base + (3 * a + 1) * 24 + 3 * a + 1]
            a2 = a2 + Kel[base + (3 * a + 2) * 24 + 3 * a + 2]
    for c in range(3):
        k = 3 * i + c
        if fixed[k] != 0:
            d[k] = 1.0
        else:
            if c == 0:
                d[k] = a0
            elif c == 1:
                d[k] = a1
            else:
                d[k] = a2
