const {chromium}=require('playwright'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const fixture=name=>path.join(__dirname,'fixtures',name);
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 await page.locator('#review-draft').setInputFiles(fixture('seed-draft.json'));await page.locator('#review-receipt').setInputFiles(fixture('seed-export-report.json'));
 await page.waitForFunction(()=>!document.querySelector('#review-bundle').disabled);
 const dir=fixture('seed-evidence-bundle');await page.locator('#review-bundle').setInputFiles(fs.readdirSync(dir).map(n=>path.join(dir,n)));
 await page.waitForFunction(()=>document.querySelector('#bundle-status').textContent.startsWith('All five'));
 await page.locator('#review-mesh').setInputFiles(process.env.FDM_PREVIEW_MESH);await page.waitForFunction(()=>document.querySelector('#review-mesh-status').textContent.startsWith('Body fingerprint matched'));
 await page.locator('#bridge-location-options > summary').click();await page.locator('#bridge-location-kind').selectOption('baseline');
 const real=fixture('bridge-locations/facet-00-shell-only.bridge-check.json'),r=JSON.parse(fs.readFileSync(real));
 await page.locator('#review-bridge').setInputFiles(real);
 await page.waitForFunction(()=>document.querySelectorAll('#bridge-location-buttons button').length===4);
 await page.locator('#bridge-location-buttons').getByRole('button',{name:'internal strand · 122.1 mm',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>reviewViewer.roadWitness),r.result.metrics.worst.internal.strand.design_mm);
 assert.match(await page.locator('#bridge-location-selected').innerText(),/Slicer roles do not prove/);
 assert.equal(await page.locator('#bridge-location-buttons [aria-pressed="true"]').count(),1);
 assert.match(await page.locator('#bridge-location-buttons [aria-pressed="true"]').innerText(),/internal strand/);
 await page.locator('#review-top').click();
 const old=await page.locator('#bridge-location-source').textContent();
 // Bad optional geometry cannot replace the valid location or any bundle measurements.
 const bad=structuredClone(r);bad.result.metrics.worst.internal.strand.design_mm.run_start[0]+=1;
 await page.locator('#review-bridge').setInputFiles({name:'bad-location.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
 await page.waitForFunction(()=>document.querySelector('#bridge-location-status').textContent.includes('coordinate frames disagree'));
 assert.equal(await page.locator('#bridge-location-source').textContent(),old);
 assert.deepEqual(await page.evaluate(()=>reviewViewer.roadWitness),r.result.metrics.worst.internal.strand.design_mm);
 await page.locator('#review-bridge').setInputFiles(fixture('bridge-locations/facet-01-shell-only.bridge-check.json'));
 await page.waitForFunction(()=>document.querySelector('#bridge-location-status').textContent.includes('differs'));
 assert.equal(await page.locator('#bridge-location-source').textContent(),old);
 await page.locator('#bridge-location-buttons').getByRole('button',{name:/internal ceiling/}).click();
 assert.deepEqual(await page.evaluate(()=>reviewViewer.roadWitness),r.result.metrics.worst.internal.ceiling.design_mm);
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#bridge-location-hide').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>reviewViewer.roadWitness),null);
 assert.match(await page.evaluate(()=>document.activeElement.textContent),/internal ceiling/);
 assert.equal(await page.locator('#bridge-location-buttons [aria-pressed="true"]').count(),0);
 await page.keyboard.press('Enter');assert.deepEqual(await page.evaluate(()=>reviewViewer.roadWitness),r.result.metrics.worst.internal.ceiling.design_mm);
 await page.locator('#bridge-location-buttons').getByRole('button',{name:/internal strand/}).click();
 await page.locator('#bridge-location-kind').selectOption('project');assert.equal(await page.evaluate(()=>reviewViewer.roadWitness),null);assert.equal(await page.locator('#bridge-location-buttons button').count(),0);
 await page.locator('#bridge-location-kind').selectOption('baseline');await page.locator('#review-bridge').setInputFiles(path.join(dir,'shell-only.bridge-check.json'));
 await page.waitForFunction(()=>document.querySelector('#bridge-location-status').textContent.includes('No location geometry recorded'));
 assert.equal(await page.locator('#bridge-location-buttons button').count(),0);assert(await page.locator('#bundle-results').isVisible());
 assert.deepEqual(errors,[]);console.log('PASS real bridge road/run/witness selection, source pairing, bad geometry retention, legacy no-overlay and mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
