// Optional browser integration: install playwright outside this repository.
const {chromium}=require('playwright');const path=require('node:path');const {pathToFileURL}=require('node:url');const fs=require('node:fs/promises');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1400,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await page.locator('#table-file').setInputFiles(path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.orientation-table.json'));const first=page.getByRole('button',{name:'facet-00',exact:true}),second=page.getByRole('button',{name:'facet-01',exact:true});
 await first.focus();await page.keyboard.press('Enter');
 assert(await first.evaluate(e=>e===document.activeElement));assert.equal(await first.getAttribute('aria-pressed'),'true');
 await page.keyboard.press('Tab');assert(await second.evaluate(e=>e===document.activeElement));
 await page.keyboard.press('Space');assert(await second.evaluate(e=>e===document.activeElement));
 assert.equal(await page.locator('#pose-name').innerText(),'facet-01');assert.equal(await second.getAttribute('aria-pressed'),'true');
 await page.keyboard.press('Shift+Tab');assert(await first.evaluate(e=>e===document.activeElement));
 await page.keyboard.press('Enter');assert(await first.evaluate(e=>e===document.activeElement));
 await page.locator('#mesh-file').setInputFiles(process.env.FDM_PREVIEW_MESH);await page.waitForFunction(()=>document.querySelector('#mesh-status').textContent.startsWith('Mesh fingerprint matched'));await page.waitForTimeout(300);assert.match(await page.locator('#metrics').innerText(),/FAIL/);await page.locator('#part-view').focus();await page.keyboard.press('ArrowRight');await page.locator('#view-top').click();await page.waitForTimeout(100);if(process.env.FDM_PREVIEW_SCREENSHOT)await page.locator('#part-view').screenshot({path:process.env.FDM_PREVIEW_SCREENSHOT});const beforeWrongMesh=await page.evaluate(()=>({vertices:Array.from(viewer.vertices),hash:meshHash,bounds:meshBounds,yaw:viewer.yaw,pitch:viewer.pitch,zoom:viewer.zoom,form:draftFormState()}));await page.locator('#mesh-file').setInputFiles({name:'wrong.stl',mimeType:'application/octet-stream',buffer:Buffer.from('wrong')});await page.waitForFunction(()=>document.querySelector('#mesh-status').textContent.includes('does not match'));assert(await page.locator('#mesh-options').evaluate(e=>e.open));assert.match(await page.locator('#mesh-status').innerText(),/previously matched mesh is retained/);assert.deepEqual(await page.evaluate(()=>({vertices:Array.from(viewer.vertices),hash:meshHash,bounds:meshBounds,yaw:viewer.yaw,pitch:viewer.pitch,zoom:viewer.zoom,form:draftFormState()})),beforeWrongMesh);await second.click();assert.equal(await page.evaluate(()=>meshHash),beforeWrongMesh.hash);assert.match(await page.locator('#mesh-status').innerText(),/Mesh fingerprint matched/);await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await browser.close();console.log('PASS real orientation import, matched STL, failed metric shown, orbit/top controls, mismatched mesh rejected, mobile overflow, console');})().catch(e=>{console.error(e);process.exit(1)});
