"""Bundle the catalog evidence for offline/file-URL UI use; no runtime YAML parser."""
import hashlib
import json
from pathlib import Path

import yaml

root = Path(__file__).resolve().parents[1]
source = root / 'catalog/slicer/orca-2.4.2-p1s-asa-modifier-capabilities.yaml'
raw = source.read_bytes()
payload = {
    'source': source.relative_to(root).as_posix(),
    'sha256': hashlib.sha256(raw).hexdigest(),
    'evidence': yaml.safe_load(raw),
}
(root / 'ui/capabilities-data.js').write_text(
    '// Generated by ui/build-capabilities.py; edit the source catalog, then regenerate.\n'
    'const modifierCapabilities = ' + json.dumps(payload, indent=2) + ';\n'
)
