// Generated by ui/build-capabilities.py; edit the source catalog, then regenerate.
const modifierCapabilities = {
  "source": "catalog/slicer/orca-2.4.2-p1s-asa-modifier-capabilities.yaml",
  "sha256": "3ec1cef19fa62282f5b9577a052834812b430907dd98f56315cfffb0dd5ceb40",
  "evidence": {
    "schema": "fdmgen/slicer-capabilities@0.1",
    "scope": "per-volume overrides on a modifier_part in an Orca 3MF (Metadata/model_settings.config)",
    "context": {
      "printer_model": "Bambu Lab P1S",
      "print_settings_id": "Part P1S ASA 4w 8-skin screen",
      "filament_settings_id": "\"ASA print-control screen\"",
      "nozzle_diameter": "0.4",
      "layer_height": "0.2",
      "wall_loops": "4",
      "sparse_infill_density": "0%",
      "wall_generator": "arachne",
      "template_3mf_sha256": "1845af11047b2307d2af8c21108b9a88e96b5318993dd735fdd7929ab8737e42",
      "slicer": "OrcaSlicer",
      "version": "2.4.2"
    },
    "method": "60 x 40 x 10 mm box body, one modifier box over its +Y end in the plate frame; one override per slice; extrusion per role inside the modifier region (segments apportioned by length) compared with a no-override baseline, and the rest of the body checked for side effects",
    "status_meaning": {
      "honoured": "the slice changed inside the region as requested",
      "ignored": "the slice did not change although the probe could show the change",
      "unknown": "the probe could not tell; keep the setting visible as unchecked"
    },
    "settings": [
      {
        "key": "sparse_infill_density",
        "requested": {
          "sparse_infill_density": "100%"
        },
        "status": "honoured",
        "measured": {
          "inside_role_delta_mm3": {
            "Gap infill": 2.0,
            "Internal Bridge": -123.4,
            "Internal solid infill": 3158.7
          }
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "sparse_infill_density=100%",
          "gcode_sha256": "27be8e6ad33a9912315016ecf717bb510ca1baef4e1c6f690a10497c0fcf722a"
        }
      },
      {
        "key": "sparse_infill_density",
        "requested": {
          "sparse_infill_density": "40%"
        },
        "status": "honoured",
        "measured": {
          "inside_role_delta_mm3": {
            "Internal Bridge": 2.8,
            "Sparse infill": 1210.7
          }
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "sparse_infill_density=40%",
          "gcode_sha256": "b2ec5bb89fac24755b0b476bbe1ab6438419618461231c329789ea4b79bf7b5b"
        }
      },
      {
        "key": "sparse_infill_pattern",
        "requested": {
          "sparse_infill_density": "40%",
          "sparse_infill_pattern": "grid"
        },
        "status": "honoured",
        "measured": {
          "diagonal_length_fraction": 0.949,
          "default_pattern_diagonal_fraction": 0.146
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "sparse_infill_pattern=grid@40%",
          "gcode_sha256": "a65b0aad3eb66b08bae6a26989c10fa3fc4839d0aea05c484cafd6a5ffde93f3"
        }
      },
      {
        "key": "wall_loops",
        "requested": {
          "wall_loops": "1"
        },
        "status": "honoured",
        "measured": {
          "wall_lines_modifier_end": 1,
          "wall_lines_far_end": 4,
          "wall_lines_internal_boundary": 5,
          "baseline_wall_lines": 4
        },
        "non_local_side_effect": "5 wall lines appear along the internal boundary between the modifier region and the body (the region gets its own perimeters, and so does the body next to it)",
        "note": null,
        "receipt": {
          "probe": "wall_loops=1",
          "gcode_sha256": "f1cee5d05dab1739f2afc4d29e9049f5151de52363ec28c6b0050a194a528c22"
        }
      },
      {
        "key": "wall_loops",
        "requested": {
          "wall_loops": "6"
        },
        "status": "honoured",
        "measured": {
          "wall_lines_modifier_end": 6,
          "wall_lines_far_end": 4,
          "wall_lines_internal_boundary": 10,
          "baseline_wall_lines": 4
        },
        "non_local_side_effect": "10 wall lines appear along the internal boundary between the modifier region and the body (the region gets its own perimeters, and so does the body next to it)",
        "note": null,
        "receipt": {
          "probe": "wall_loops=6",
          "gcode_sha256": "1fa3afb7ca6240a0b1c67eaf354faa0dc03699776efd84ffbdc7784d8765bdc3"
        }
      },
      {
        "key": "top_shell_layers",
        "requested": {
          "top_shell_layers": "2",
          "top_shell_thickness": "0"
        },
        "status": "honoured",
        "measured": {
          "inside_role_delta_mm3": {
            "Internal Bridge": 123.4,
            "Internal solid infill": -538.4
          }
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "top_shell_layers=2",
          "gcode_sha256": "cb522c2ebba1a7e178aa73796515718b1d24edb67be17c3224776d3810a8517e"
        }
      },
      {
        "key": "bottom_shell_layers",
        "requested": {
          "bottom_shell_layers": "2",
          "bottom_shell_thickness": "0"
        },
        "status": "honoured",
        "measured": {
          "inside_role_delta_mm3": {
            "Internal solid infill": -542.4
          }
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "bottom_shell_layers=2",
          "gcode_sha256": "c639b2457b79448782bd10c49ee1bde60bb56a1540c1e473d43c51710da6fcee"
        }
      },
      {
        "key": "top_shell_layers",
        "requested": {
          "top_shell_layers": "15",
          "top_shell_thickness": "0"
        },
        "status": "honoured",
        "measured": {
          "inside_role_delta_mm3": {
            "Internal solid infill": 631.5
          }
        },
        "non_local_side_effect": "volume outside the modifier region changes by +6.1 %",
        "note": null,
        "receipt": {
          "probe": "top_shell_layers=15",
          "gcode_sha256": "bc830767925ce35841acd44447b50a6d0ce997a454d6563e4f97cb07824e4524"
        }
      },
      {
        "key": "wall_generator",
        "requested": {
          "wall_generator": "classic"
        },
        "status": "ignored",
        "measured": {
          "probe": "tapered wall 0.6 -> 2.4 mm, modifier over half of it",
          "inside_wall_widths_distinct": 32,
          "inside_gap_infill_mm3": 0.0,
          "baseline_arachne_inside_wall_widths_distinct": 32,
          "positive_control_object_classic_inside_wall_widths_distinct": 2,
          "positive_control_object_classic_inside_gap_infill_mm3": 66.37
        },
        "non_local_side_effect": null,
        "note": "the per-modifier value is dropped: the region keeps Arachne walls (32 bead widths, no gap fill) while the same key on the whole object gives classic walls (2 widths, 66 mm3 gap fill); wall_generator is an object-level setting",
        "receipt": {
          "probe": "wall_generator=classic (taper)",
          "gcode_sha256": "7432fd816252ddf49782ed4bea0dc1e65e6ad61d41ab32978b9ab33dc14ba55f",
          "positive_control_gcode_sha256": "b47e9f5984cd4cc85ac97dbbe1b79c4435ddd37ae5ff3685f400c0fa3c99e812",
          "slicer_build": "OrcaSlicer 2.4.2, Windows executable sha256 481c9f071fdb3cda033d1677ce7a9442c41a25cbeeb42cfc808af179b4dc85c3"
        }
      },
      {
        "key": "outer_wall_line_width",
        "requested": {
          "outer_wall_line_width": "0.6"
        },
        "status": "honoured",
        "measured": {
          "mean_declared_width_mm": 0.5978
        },
        "non_local_side_effect": "8 wall lines appear along the internal boundary between the modifier region and the body (the region gets its own perimeters, and so does the body next to it)",
        "note": null,
        "receipt": {
          "probe": "outer_wall_line_width=0.6",
          "gcode_sha256": "dd56b4b2861305d63bf5a4342e8b4f52ac78e12ce9a6d95f958f36bddee94d43"
        }
      },
      {
        "key": "inner_wall_line_width",
        "requested": {
          "inner_wall_line_width": "0.6"
        },
        "status": "honoured",
        "measured": {
          "mean_declared_width_mm": 0.5978
        },
        "non_local_side_effect": "8 wall lines appear along the internal boundary between the modifier region and the body (the region gets its own perimeters, and so does the body next to it)",
        "note": null,
        "receipt": {
          "probe": "inner_wall_line_width=0.6",
          "gcode_sha256": "265a033af6405fc019567165980417ed163514293c2f4095fc7d4ad58e3ba1e8"
        }
      },
      {
        "key": "sparse_infill_line_width",
        "requested": {
          "sparse_infill_density": "40%",
          "sparse_infill_line_width": "0.6"
        },
        "status": "honoured",
        "measured": {
          "mean_declared_width_mm": 0.6
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "sparse_infill_line_width=0.6@40%",
          "gcode_sha256": "239f001c3632ee53f4644e6a46d2669d1ddc430e5a08417e731448bfdf6c2185"
        }
      },
      {
        "key": "layer_height",
        "requested": {
          "layer_height": "0.1"
        },
        "status": "ignored",
        "measured": {
          "layer_heights_mm": [
            0.2,
            0.4
          ]
        },
        "non_local_side_effect": null,
        "note": null,
        "receipt": {
          "probe": "layer_height=0.1",
          "gcode_sha256": "a84ff04c9f8a22cf321b02ca4e14979c6e535a975c80bc39c71991724ff90c83"
        }
      }
    ],
    "establishes": "What this Orca version does with these overrides in this profile context (tier S).",
    "does_not_establish": "Behaviour in other Orca versions or profiles, or how the printed regions perform."
  }
};
