const {chromium}=require('playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 const root=path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.with-keep-outs'),bytes=fs.readFileSync(root+'.orientation-table.json'),table=JSON.parse(bytes),sha=crypto.createHash('sha256').update(bytes).digest('hex');
 const geometry=JSON.parse(fs.readFileSync(process.env.FDM_INTERFACE_FIXTURE||root+'.interface-render.json'));assert.equal(geometry.table.sha256,sha);
 await p.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await p.locator('#table-file').setInputFiles(root+'.orientation-table.json');await p.locator('#draft-file').setInputFiles(path.join(__dirname,'fixtures/seed-draft.json'));await p.waitForFunction(()=>document.querySelectorAll('.helper-region').length===6);
 const helper=p.locator('.helper-region').first(),locate=helper.locator('[data-locate-interfaces]');
 const checkedBefore=await helper.locator('[data-interface-id]:checked').evaluateAll(fields=>fields.map(field=>field.dataset.interfaceId));
 for(const field of await helper.locator('[data-interface-id]').all())await field.uncheck();
 const noRefs=await p.evaluate(()=>workSnapshot());await locate.click();assert.match(await p.locator('#interface-status').innerText(),/no selected interface references/);assert.deepEqual(await p.evaluate(()=>workSnapshot()),noRefs);
 for(const id of checkedBefore)await helper.locator(`[data-interface-id="${id}"]`).check();
 const before=await p.evaluate(()=>workSnapshot());await locate.click();assert(await p.locator('#interface-file').evaluate(e=>e===document.activeElement));assert.deepEqual(await p.evaluate(()=>workSnapshot()),before);
 await p.locator('#interface-options').evaluate(e=>e.open=true);
 const upload=async g=>{await p.locator('#interface-file').setInputFiles({name:'interfaces.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(g))});await p.waitForFunction(()=>document.getElementById('interface-file').value==='');};
 await upload(geometry);assert.match(await p.locator('#interface-status').innerText(),/fingerprints matched/);
 await locate.click();assert(await p.locator('#mesh-file').evaluate(e=>e===document.activeElement));assert.deepEqual(await p.evaluate(()=>workSnapshot()),before);
 await p.locator('#hide-interfaces').click();
 await p.locator('[data-interface-preview="rear_seat"]').check();assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);assert.match(await p.locator('#interface-visible-names').innerText(),/load the matched STL/);
 // Pending and suppressed envelopes remain explained outside collapsed controls.
 const pendingWork=await p.evaluate(()=>workSnapshot());await p.locator('#preview-helper-clearance').check();await p.locator('#interface-options').evaluate(e=>e.open=false);
 assert(await p.locator('#interface-visibility').isVisible());assert.match(await p.locator('#interface-visible-names').innerText(),/Load the matched STL and select a pose to draw/);assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);assert.deepEqual(await p.evaluate(()=>workSnapshot()),pendingWork);
 await p.locator('#interface-options').evaluate(e=>e.open=true);await p.locator('#preview-helper-clearance').uncheck();
 await p.locator('#mesh-file').setInputFiles(process.env.FDM_PREVIEW_MESH);await p.waitForFunction(()=>viewer.interfaces.length===1);
 assert.equal(await p.evaluate(()=>viewer.interfaces[0].base_radius_mm),13.6);assert.deepEqual(await p.evaluate(()=>workSnapshot()),before);
 for(const field of await helper.locator('[data-interface-id]').all())await field.setChecked((await field.getAttribute('data-interface-id'))==='rear_seat');
 const refState=await p.evaluate(()=>workSnapshot());await locate.click();assert.deepEqual(await p.evaluate(()=>viewer.interfaces.map(item=>item.id)),['rear_seat']);assert.deepEqual(await p.evaluate(()=>workSnapshot()),refState);assert(await p.locator('#part-view').evaluate(e=>e===document.activeElement));
 await helper.locator('[data-interface-id="rear_seat"]').uncheck();const emptyState=await p.evaluate(()=>workSnapshot());await locate.click();assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);assert.match(await p.locator('#interface-status').innerText(),/no selected interface references/);assert.deepEqual(await p.evaluate(()=>workSnapshot()),emptyState);
 await helper.locator('[data-interface-id="rear_seat"]').check();await locate.click();
 const extra=helper.locator('[data-clearance]'),savedExtra=await extra.inputValue();
 await extra.fill('2');const envelopeState=await p.evaluate(()=>workSnapshot());await p.locator('#preview-helper-clearance').check();assert.deepEqual(await p.evaluate(()=>workSnapshot()),envelopeState);
 assert.deepEqual(await p.evaluate(()=>viewer.interfaces.filter(item=>item.clearance).map(item=>[item.id,item.extra_clearance_mm])),[['rear_seat',2]]);assert.match(await p.locator('#helper-clearance-status').innerText(),/15.6 mm radius/);
 await extra.fill('');assert.match(await p.locator('#helper-clearance-status').innerText(),/blank clearance uses 0/);assert.equal(await p.evaluate(()=>viewer.interfaces.find(item=>item.clearance).extra_clearance_mm),0);
 await extra.fill('-1');assert.equal(await p.evaluate(()=>viewer.interfaces.filter(item=>item.clearance).length),0);assert.match(await p.locator('#helper-clearance-status').innerText(),/invalid extra clearance/);
 await p.locator('[data-interface-preview="rear_seat"]').uncheck();await p.locator('#interface-options').evaluate(e=>e.open=false);
 assert(await p.locator('#interface-visibility').isVisible());assert.match(await p.locator('#interface-visible-names').innerText(),/invalid extra clearance.*No clearance envelope drawn/);assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);
 await extra.fill('2');assert.match(await p.locator('#interface-visible-names').innerText(),/envelope shown/);assert.equal(await p.evaluate(()=>viewer.interfaces.length),1);
 await helper.locator('[data-interface-id="rear_seat"]').uncheck();assert(await p.locator('#interface-visibility').isVisible());assert.match(await p.locator('#interface-visible-names').innerText(),/no interface references selected/);assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);
 await helper.locator('[data-interface-id="rear_seat"]').check();await p.locator('#interface-options').evaluate(e=>e.open=true);
 await extra.fill(savedExtra);await p.locator('.helper-region').nth(1).locator('[data-key="name"]').focus();assert.equal(await p.evaluate(()=>viewer.interfaces.filter(item=>item.clearance).length),4);
 await p.locator('#shell-only').check();assert.equal(await p.evaluate(()=>viewer.interfaces.filter(item=>item.clearance).length),0);assert.match(await p.locator('#helper-clearance-status').innerText(),/Shell-only plan/);await p.locator('#shell-only').uncheck();
 await locate.click();await p.locator('#preview-helper-clearance').uncheck();assert.equal(await p.evaluate(()=>viewer.interfaces.filter(item=>item.clearance).length),0);
 const lines=await p.evaluate(()=>viewer.interfaces[0].lines);await p.getByRole('button',{name:'facet-01',exact:true}).click();assert.deepEqual(await p.evaluate(()=>viewer.interfaces[0].lines),lines);assert.deepEqual(await p.evaluate(()=>viewer.R),table.candidates.find(c=>c.id==='facet-01').R_design_to_print);
 await p.getByRole('button',{name:'facet-00',exact:true}).click();
 await p.locator('[data-interface-preview="mount_upper"]').check();
 await p.locator('#part-view').scrollIntoViewIfNeeded();await p.waitForFunction(()=>!viewer.pending);
 const miss=await p.evaluate(()=>{const rect=viewer.canvas.getBoundingClientRect();for(const item of viewer.interfaces)for(const line of item.lines){const d=line[0].map((x,k)=>(x+line[1][k])/2),v=transformMesh(d,viewer.R,viewer.t),q=viewer.project(...v);if(q[0]>140&&q[0]<rect.width-10&&q[1]>110&&q[1]<rect.height-70&&!pickSurface(viewer.vertices,viewer.project,q[0],q[1]))return [rect.left+q[0],rect.top+q[1]];}return null;});
 assert(miss,'a visible cylinder line outside the body is available for a pick-miss control');
 await p.evaluate(()=>{window.interfacePick='not called';viewer.onPick=point=>window.interfacePick=point;});await p.mouse.click(...miss);assert.equal(await p.evaluate(()=>window.interfacePick),null);await p.evaluate(()=>viewer.onPick=null);
 const retained=await p.evaluate(()=>({geometry:interfaceGeometry,lines:viewer.interfaces,work:workSnapshot()}));
 for(const edit of [g=>g.table.sha256='0'.repeat(64),g=>g.items[0].base_radius_mm+=1,g=>g.items.pop()]){const bad=structuredClone(geometry);edit(bad);await upload(bad);assert.match(await p.locator('#interface-status').innerText(),/retained/);assert.deepEqual(await p.evaluate(()=>({geometry:interfaceGeometry,lines:viewer.interfaces,work:workSnapshot()})),retained);}
 assert.match(await p.locator('#interface-visible-names').innerText(),/no helper extra clearance/);
 if(process.env.FDM_INTERFACE_SCREENSHOT)await p.locator('.preview').screenshot({path:process.env.FDM_INTERFACE_SCREENSHOT});
 await p.locator('#hide-interfaces').click();assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);assert.deepEqual(await p.evaluate(()=>workSnapshot()),retained.work);
 await p.locator('[data-interface-preview="mount_upper"]').check();await p.locator('#table-file').setInputFiles([]);await p.locator('#table-file').setInputFiles(root+'.orientation-table.json');await p.waitForFunction(()=>interfaceGeometry===null);assert.equal(await p.evaluate(()=>viewer.interfaces.length),0);
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS real producer interface import/frame binding, mesh gate, pose persistence, overlay-only pick miss, malformed retention, explicit visibility, no draft mutation and mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
