const {chromium}=require('playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',dialog=>dialog.accept());
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
 await page.locator('#table-file').setInputFiles(path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.orientation-table.json'));await page.getByRole('button',{name:'facet-00',exact:true}).click();
 assert.equal(await page.locator('[data-keep-out-id]').count(),0);
 await page.locator('#table-file').setInputFiles(path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.with-keep-outs.orientation-table.json'));await page.getByRole('button',{name:'facet-00',exact:true}).click();
 await page.locator('#rationale').fill('Track assembly clearance while planning rear-seat reinforcement.');
 const box=page.locator('.helper-region').first();
 const beforeDetails=await page.evaluate(()=>draftFormState());
 const declaration=box.locator('[data-interface-detail="rear_seat"]');
 await declaration.locator('summary').focus();await declaration.locator('summary').press('Enter');
 assert.match(await declaration.innerText(),/Model: rod_seat. Axis: Z. Support: forbidden/);
 assert.match(await declaration.innerText(),/Frame: not declared in this interface/);
 const originalTable=JSON.parse(await fs.readFile(path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.with-keep-outs.orientation-table.json')));
 assert.deepEqual(JSON.parse(await declaration.locator('pre').textContent()),originalTable.interfaces.find(i=>i.id==='rear_seat'));
 assert.equal(await page.evaluate(()=>draftFormState()),beforeDetails);
 for(const [key,value]of Object.entries({name:'Rear seat backing',location:'Below rear seat',purpose:'Transfer seat load',keep_clear:'Retain moulding and spool-slide clearance; validate with backend'}))await box.locator(`[data-key="${key}"]`).fill(value);
 await box.locator('[data-spatial]').check();
 for(let i=0;i<3;i++){await box.locator(`[data-geometry="center_mm"][data-axis="${i}"]`).fill(String([90,-18,12][i]));await box.locator(`[data-geometry="size_mm"][data-axis="${i}"]`).fill(String([16,10,20][i]));}
 await box.locator('[data-keep-out-id="crown_moulding"]').check();await box.locator('[data-keep-out-id="spool_slide"]').check();
 await box.getByText('crown_moulding constraint',{exact:true}).click();assert.match(await box.innerText(),/Declared frame: installed/);assert.match(await box.innerText(),/global constraints still apply/);
 const wait=page.waitForEvent('download');await page.locator('#export').click();const download=await wait,raw=await fs.readFile(await download.path()),draft=JSON.parse(raw);
 assert.deepEqual(draft.massing.helper_regions[0].keep_clear.keep_out_ids,['crown_moulding','spool_slide']);
 if(process.env.FDM_KEEP_OUT_DRAFT)await fs.writeFile(process.env.FDM_KEEP_OUT_DRAFT,raw);
 await box.locator('[data-keep-out-id="spool_slide"]').uncheck();
 await page.locator('#draft-file').setInputFiles({name:'saved.json',mimeType:'application/json',buffer:raw});await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.startsWith('Draft restored'));
 assert(await box.locator('[data-keep-out-id="spool_slide"]').isChecked());
 draft.massing.helper_regions[0].keep_clear.keep_out_ids.push('unknown');
 await page.locator('#draft-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(draft))});await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.includes('Unknown keep-out'));
 assert(await box.locator('[data-keep-out-id="spool_slide"]').isChecked());
 // Geometry is optional view state; wrong pins retain the previous preview.
 const draftState=await page.evaluate(()=>draftFormState());
 const geometryPath=path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.with-keep-outs.keepout-render.json');
 await page.locator('#keepout-options summary').first().click();
 await page.locator('#keepout-file').setInputFiles(geometryPath);
 await page.waitForFunction(()=>document.querySelector('#keepout-status').textContent.startsWith('Table and mesh'));
 await page.locator('#mesh-file').setInputFiles(process.env.FDM_PREVIEW_MESH);
 await page.waitForFunction(()=>!!viewer.vertices);
 const before=await page.locator('#part-view').screenshot();
 await page.locator('[data-keepout-preview="crown_moulding"]').check();
 await page.waitForFunction(()=>viewer.keepouts.length===1&&!viewer.pending);
 assert.notDeepEqual(await page.locator('#part-view').screenshot(),before);
 assert.deepEqual(await page.evaluate(()=>viewer.keepouts.map(x=>x.id)),['crown_moulding']);
 await page.locator('[data-keepout-preview="spool_slide"]').check();
 await page.waitForFunction(()=>viewer.keepouts.length===2&&!viewer.pending);
 assert.equal(await page.evaluate(()=>draftFormState()),draftState);
 await page.locator('#keepout-options > summary').click();
 assert(await page.locator('#keepout-visibility').isVisible());
 assert.match(await page.locator('#keepout-visible-names').innerText(),/crown_moulding, spool_slide/);
 await page.locator('#hide-keepouts').focus();await page.keyboard.press('Enter');
 assert.equal(await page.evaluate(()=>viewer.keepouts.length),0);
 assert(await page.locator('#keepout-visibility').isHidden());
 assert(await page.locator('#part-view').evaluate(e=>e===document.activeElement));
 assert.equal(await page.evaluate(()=>draftFormState()),draftState);
 await page.locator('#keepout-options > summary').click();
 assert(!(await page.locator('[data-keepout-preview="crown_moulding"]').isChecked()));
 assert(!(await page.locator('[data-keepout-preview="spool_slide"]').isChecked()));
 // Geometry remains loaded and can be shown again without another file import.
 await page.locator('[data-keepout-preview="crown_moulding"]').check();
 await page.locator('[data-keepout-preview="spool_slide"]').check();
 const geometry=JSON.parse(await fs.readFile(geometryPath));geometry.table.sha256='0'.repeat(64);
 await page.locator('#keepout-file').setInputFiles({name:'wrong-table.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(geometry))});
 await page.waitForFunction(()=>document.querySelector('#keepout-status').textContent.includes('different table bytes'));
 assert.equal(await page.evaluate(()=>viewer.keepouts.length),2);
 assert(await page.locator('[data-keepout-preview="spool_slide"]').isChecked());
 assert.equal(await page.evaluate(()=>draftFormState()),draftState);
 await page.locator('#keepout-provenance summary').click();
 assert.match(await page.locator('#keepout-source').textContent(),/envelope between samples is not drawn/);
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#keepout-provenance summary').click();
 await page.setViewportSize({width:1366,height:900});
 if(process.env.FDM_KEEPOUT_SCREENSHOT)await page.locator('.preview').screenshot({path:process.env.FDM_KEEPOUT_SCREENSHOT});
 await page.locator('#table-file').setInputFiles(path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.orientation-table.json'));
 await page.waitForFunction(()=>document.querySelector('#keepout-status').textContent==='No keep-out geometry loaded.');
 assert.equal(await page.evaluate(()=>viewer.keepouts.length),0);
 assert.equal(await page.locator('[data-keepout-preview]').count(),0);
 assert(await page.locator('#keepout-visibility').isHidden());
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS historical/new table keep-out declarations, selection/export/reopen, unknown ref rejected without replacing draft, mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
