const {chromium}=require('playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({locale:'en-US'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 assert(await page.locator('#review-draft').isVisible());assert(await page.locator('#review-bundle').isVisible());
 assert(await page.locator('#review-slice').isHidden());
 const manual=page.locator('#individual-receipts > summary');await manual.focus();await manual.press('Enter');
 assert(await page.locator('#review-slice').isVisible());assert(await page.locator('#review-mechanics').isVisible());
 const draftPath=path.join(__dirname,'../tests/fixtures/massing/sample-draft.json'),receiptPath=path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json');
 await page.locator('#review-draft').setInputFiles(draftPath);await page.locator('#review-receipt').setInputFiles(receiptPath);
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.startsWith('Receipt fingerprint matched'));
 const sha=file=>require('node:crypto').createHash('sha256').update(fs.readFileSync(file)).digest('hex');
 const report=JSON.parse(fs.readFileSync(receiptPath));
 await page.getByText('Current input fingerprints (SHA-256)',{exact:true}).click();
 const expectedHashes=[sha(draftPath),sha(receiptPath),report.plan.table_sha256,report.template_3mf_sha256,report.project_3mf_sha256];
 assert.deepEqual(await page.locator('#review-input-hashes code').allTextContents(),expectedHashes);
 assert.match(await page.locator('#review-input-hashes').innerText(),/Export report — calculated/);
 const sliceNav=page.locator('[data-review-target="slice-results"]');
 assert(await sliceNav.isDisabled());assert.match(await sliceNav.innerText(),/not loaded/);
 await page.locator('[data-review-target="helper-results"]').click();
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Helpers in this export');
 const checks=JSON.parse(fs.readFileSync(receiptPath)).checks;
 assert.equal(await page.locator('#review-checks article').count(),checks.filter(c=>c.verdict!=='PASS').length);
 await page.locator('#check-filter').selectOption('all');assert.equal(await page.locator('#review-checks article').count(),checks.length);
 await page.locator('#check-filter').selectOption('NOT_CHECKED');assert.equal(await page.locator('#review-checks article').count(),checks.filter(c=>c.verdict==='NOT_CHECKED').length);
 await page.locator('#check-filter').selectOption('attention');
 assert.match(await page.locator('#review-checks').innerText(),/Deliberately tiny box/);assert.match(await page.locator('#review-count').innerText(),/2 failed/);assert.match(await page.locator('#review-helpers').innerText(),/Rear seat backing/);assert.match(await page.locator('#review-setting-evidence').innerText(),/sparse_infill_density/);
 const changed=JSON.parse(fs.readFileSync(receiptPath));changed.capability_context_matches_template=false;
 await page.locator('#review-receipt').setInputFiles({name:'different-context.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(changed))});
 await page.waitForFunction(()=>document.querySelector('#review-context').textContent.includes('Template differs'));
 const evidencePath=path.join(__dirname,'../tests/fixtures/massing/sample-slice-evidence.json');
 await page.locator('#review-slice').setInputFiles(evidencePath);
 await page.waitForFunction(()=>document.querySelector('#slice-status').textContent.startsWith('Slice receipt matches'));
 assert(await sliceNav.isEnabled());await sliceNav.click();
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'What changed in the slice');
 await page.getByText('Project and baseline slicer settings',{exact:true}).click();assert.match(await page.locator('#slice-settings').innerText(),/gcode_sha256/);assert.match(await page.locator('#slice-settings').innerText(),/2.4.2/);
 assert.match(await page.locator('#slice-helpers').innerText(),/Rear seat backing · T PASS/);assert.match(await page.locator('#slice-helpers').innerText(),/Deliberately tiny box · T FAIL/);assert((await page.locator('#slice-helpers').innerText()).includes(JSON.parse(fs.readFileSync(evidencePath)).helpers[0].added_solid_mm3.toLocaleString('en-US',{maximumFractionDigits:3})));
 const incompatible=JSON.parse(fs.readFileSync(evidencePath));incompatible.slicer={layer_height:'0.2'};incompatible.baseline_slicer={layer_height:'0.3'};incompatible.baseline_context_mismatch=[];
 await page.locator('#review-slice').setInputFiles({name:'context.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incompatible))});
 await page.waitForFunction(()=>document.querySelector('#slice-baseline').textContent.includes('Baseline settings differ'));assert.match(await page.locator('#slice-helpers').innerText(),/context mismatch/);
 const noBaseline=JSON.parse(fs.readFileSync(evidencePath));noBaseline.baseline=null;for(const h of noBaseline.helpers)h.baseline_solid_infill_mm3=null;
 await page.locator('#review-slice').setInputFiles({name:'absolute.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(noBaseline))});
 await page.waitForFunction(()=>document.querySelector('#slice-baseline').textContent.startsWith('No shell-only'));
 assert.match(await page.locator('#slice-helpers').innerText(),/Not attributable without baseline/);
 noBaseline.project_3mf_sha256='0'.repeat(64);
 await page.locator('#review-slice').setInputFiles({name:'wrong-slice.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(noBaseline))});
 await page.waitForFunction(()=>document.querySelector('#slice-status').textContent.includes('different exported project'));assert(await page.locator('#slice-results').isVisible());
 await page.locator('#review-receipt').setInputFiles(receiptPath);await page.waitForFunction(()=>document.querySelector('#slice-results').hidden);assert.match(await page.locator('#slice-status').innerText(),/No slice evidence loaded/);
 assert(await sliceNav.isDisabled());
 changed.plan.draft_sha256='0'.repeat(64);
 await page.locator('#review-receipt').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(changed))});
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.includes('does not match'));
 assert(await page.locator('#review-workspace').isVisible());
 assert.deepEqual(await page.locator('#review-input-hashes code').allTextContents(),expectedHashes,'Rejected replacement retains the matched input identities');
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#review-draft').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{}')});
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.includes('current planning draft'));
 assert(await page.locator('#review-workspace').isHidden());assert(await page.locator('#review-receipt').isDisabled());assert.deepEqual(errors,[]);
 await page.locator('#review-draft').setInputFiles(path.join(__dirname,'fixtures/revised-draft.json'));
 await page.locator('#review-receipt').setInputFiles(path.join(__dirname,'fixtures/revised-export-report.json'));
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.startsWith('Receipt fingerprint matched'));
 assert.equal(await page.locator('#check-filter').inputValue(),'attention');
 assert.equal(await page.locator('#review-checks article').count(),0);
 assert.match(await page.locator('#check-filter-status').innerText(),/does not qualify the part/);
 await page.locator('#check-filter').selectOption('PASS');
 assert.match(await page.locator('#review-checks').innerText(),/15.00 mm/);
 await page.locator('#review-slice').setInputFiles(path.join(__dirname,'fixtures/revised-slice-evidence.json'));
 await page.waitForFunction(()=>document.querySelector('#slice-status').textContent.startsWith('Slice receipt matches'));
 assert.match(await page.locator('#slice-helpers').innerText(),/3,167.195/);
 assert.match(await page.locator('#slice-helpers').innerText(),/T PASS/);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 // Synthetic display-name collision; pin the report to the exact modified draft bytes.
 const duplicateDraft=JSON.parse(fs.readFileSync(draftPath));
 duplicateDraft.massing.helper_regions.forEach(h=>h.name='Shared helper');
 const duplicateBytes=Buffer.from(JSON.stringify(duplicateDraft)),duplicateReport=JSON.parse(fs.readFileSync(receiptPath));
 duplicateReport.plan.draft_sha256=require('node:crypto').createHash('sha256').update(duplicateBytes).digest('hex');
 await page.locator('#review-draft').setInputFiles({name:'same-names.json',mimeType:'application/json',buffer:duplicateBytes});
 await page.locator('#review-receipt').setInputFiles({name:'same-names-report.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(duplicateReport))});
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.startsWith('Receipt fingerprint matched'));
 const labels=duplicateDraft.massing.helper_regions.map(h=>`Shared helper [${h.id}]`);
 assert.deepEqual(await page.locator('#review-helpers h3').allTextContents(),labels);
 const checkText=await page.locator('#review-checks').innerText();
 for(const h of duplicateDraft.massing.helper_regions)assert(!checkText.includes(`[${h.id}] [${h.id}]`));
 assert.deepEqual(await page.evaluate(()=>saved.massing.helper_regions.map(h=>h.name)),['Shared helper','Shared helper']);
 await page.locator('#review-helpers').getByRole('button',{name:`Edit ${labels[1]}`,exact:true}).click();
 await page.waitForURL('**/index.html#review-edit');
 const transfer=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('fdmgen-review-edit')));
 assert.equal(transfer.helper_id,duplicateDraft.massing.helper_regions[1].id);
 assert.deepEqual(transfer.draft.massing,duplicateDraft.massing);
 assert.deepEqual(errors,[]);
 console.log('PASS real exporter receipt/draft pairing, named tiny helper failure, context mismatch, wrong receipt retention, new draft invalidation, mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
