const {chromium}=require('playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({locale:'en-US'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 const fixture=name=>path.join(__dirname,'fixtures/seed-'+name+'.json'),receipt=path.join(__dirname,'../bench/receipts/occupancy-connected-sensitivity-r1.json');
 await page.locator('#review-draft').setInputFiles(fixture('draft'));
 await page.locator('#review-receipt').setInputFiles(fixture('export-report'));
 await page.waitForFunction(()=>document.querySelector('#review-status').textContent.startsWith('Receipt fingerprint matched'));
 assert(await page.locator('#review-mechanics').isDisabled());
 await page.locator('#review-slice').setInputFiles(fixture('slice-evidence'));
 await page.waitForFunction(()=>document.querySelector('#slice-status').textContent.startsWith('Slice receipt matches'));
 await page.locator('#review-mechanics').setInputFiles(receipt);
 await page.waitForFunction(()=>document.querySelector('#mechanics-status').textContent.startsWith('Mechanics receipt matches'));
 assert.match(await page.locator('#mechanics-policy').innerText(),/Fragments were explicitly removed/);
 assert.match(await page.locator('#mechanics-comparison').innerText(),/-2.924%/);
 assert.match(await page.locator('#mechanics-rows').innerText(),/484.839/);
 assert.match(await page.locator('#mechanics-audits').innerText(),/Removed 52 cells/);
 assert.match(await page.locator('#mechanics-resolution').innerText(),/Solver cell size: 1.6 × 1.6 × 1.6 mm/);
 assert.match(await page.locator('#mechanics-sampling').innerText(),/Shell-only bead sampling step: not recorded/);
 await page.locator('#review-mechanics').setInputFiles(path.join(__dirname,'../bench/receipts/occupancy-connected-sampling16-r1.json'));
 await page.waitForFunction(()=>document.querySelector('#mechanics-comparison').textContent.includes('-2.988%'));
 assert.match(await page.locator('#mechanics-sampling').innerText(),/Shell-only bead sampling step: 0.1 mm. Project bead sampling step: 0.1 mm/);
 assert.match(await page.locator('#mechanics-resolution').innerText(),/1.6 × 1.6 × 1.6 mm/);
 assert.match(await page.locator('#mechanics-sampling').innerText(),/Shell-only road-end\/turn caps: not recorded/);
 await page.locator('#review-mechanics').setInputFiles(path.join(__dirname,'../bench/receipts/occupancy-caps-sf16-connected-r1.json'));
 await page.waitForFunction(()=>document.querySelector('#mechanics-comparison').textContent.includes('-2.288%'));
 assert.match(await page.locator('#mechanics-sampling').innerText(),/Shell-only road-end\/turn caps: enabled. Project road-end\/turn caps: enabled/);
 assert.match(await page.locator('#mechanics-rows').innerText(),/485.325/);
 const disabled=JSON.parse(fs.readFileSync(receipt));for(const v of Object.values(disabled.inputs))v.provenance.sampling={caps:false};
 await page.locator('#review-mechanics').setInputFiles({name:'synthetic-caps-off.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(disabled))});
 await page.waitForFunction(()=>document.querySelector('#mechanics-sampling').textContent.includes('Project road-end/turn caps: disabled'));
 const wrong=JSON.parse(fs.readFileSync(receipt));wrong.inputs.baseline.provenance.gcode_sha256='a'.repeat(64);
 await page.locator('#review-mechanics').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(wrong))});
 await page.waitForFunction(()=>document.querySelector('#mechanics-status').textContent.includes('baseline G-code differs'));
 assert(await page.locator('#mechanics-results').isVisible());
 await page.locator('#review-mechanics').setInputFiles(path.join(__dirname,'../bench/receipts/occupancy-seat-transfer-r1.json'));
 await page.waitForFunction(()=>document.querySelector('#mechanics-comparison').textContent.includes('No supported compliance comparison'));
 assert.match(await page.locator('#mechanics-rows').innerText(),/Not established/);assert.match(await page.locator('#mechanics-audits').innerText(),/face-connected components/);
 for(const [power,delta] of [[1,'-1.738%'],[3,'-2.906%']]){
  const weightedPath=path.join(__dirname,`../bench/receipts/occupancy-density-p${power}-sf16-r1.json`);
  await page.locator('#review-mechanics').setInputFiles(weightedPath);
  await page.waitForFunction(delta=>document.querySelector('#mechanics-comparison').textContent.includes(delta),delta);
  assert.match(await page.locator('#mechanics-policy').innerText(),/Density-weighted stiffness, no binary threshold/);
  assert.match(await page.locator('#mechanics-model').innerText(),new RegExp(`power ${power}, stiffness floor 0`));
  assert.match(await page.locator('#mechanics-model').innerText(),/no transfer or deletion/);
  assert.match(await page.locator('#mechanics-model').innerText(),/uncalibrated/);
  assert.match(await page.locator('#mechanics-audits').innerText(),/Raw domain: blocked/);
  assert.deepEqual(JSON.parse(await page.locator('#mechanics-provenance').textContent()),JSON.parse(fs.readFileSync(weightedPath)));
 }
 const badWeighted=JSON.parse(fs.readFileSync(path.join(__dirname,'../bench/receipts/occupancy-density-p3-sf16-r1.json')));
 badWeighted.cases.project.audit.missing_load_l1_N=1;
 await page.locator('#review-mechanics').setInputFiles({name:'synthetic-lost-load.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(badWeighted))});
 await page.waitForFunction(()=>document.querySelector('#mechanics-comparison').textContent.includes('No supported compliance comparison'));
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#review-slice').setInputFiles([]);await page.locator('#review-slice').setInputFiles(fixture('slice-evidence'));
 await page.waitForFunction(()=>document.querySelector('#mechanics-results').hidden);
 await page.locator('#review-mechanics').setInputFiles(receipt);await page.waitForFunction(()=>!document.querySelector('#mechanics-results').hidden);
 await page.locator('#review-draft').setInputFiles([]);await page.locator('#review-draft').setInputFiles(fixture('draft')); // A new selection invalidates downstream results.
 await page.waitForFunction(()=>document.querySelector('#mechanics-results').hidden);
 assert(await page.locator('#review-mechanics').isDisabled());assert.deepEqual(errors,[]);
 console.log('PASS real mechanics pairing, domain scope, raw blocked result, wrong baseline rejection, invalidation and mobile');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
