const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});try{
 const p=await b.newPage({viewport:{width:1366,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 const dir=path.join(__dirname,'fixtures/orient-evidence-roads'),sha=v=>crypto.createHash('sha256').update(v).digest('hex');
 // Exact complete producer output, preserved without reserialising any receipt or manifest.
 const data=new Map(fs.readdirSync(dir).map(n=>[n,fs.readFileSync(path.join(dir,n))])),m=JSON.parse(data.get('orient-evidence.json'));
 assert.equal(sha(data.get('orient-evidence.json')),'e1428bf185be2f328473cdd0b4dc4bf802473cee51fde7c2f76d33c6bdf44bd0');
 assert.equal(sha(data.get(m.enriched_table.path)),'3930a5e60a2db0fe50ac03376aca04cba136e43dba9f89e50282fb217f1cb52b');
 for(const e of m.receipts) assert.equal(sha(data.get(e.path)),e.sha256);
 const files=()=>[...data].map(([name,buffer])=>({name,buffer,mimeType:'application/json'}));
 await p.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await p.locator('#orientation-bundle-options > summary').click();await p.locator('#orientation-bundle-files').setInputFiles(files());
 await p.waitForFunction(()=>document.querySelector('#orientation-bundle-status').textContent.startsWith('Complete bundle verified'));
 await p.getByRole('button',{name:'Review facet-01',exact:true}).click();
 assert.equal(await p.locator('#pose-road-buttons button').count(),4);
 const before=await p.evaluate(()=>draftFormState());
 await p.locator('[data-locate-failed-bridge=external]').click();
 assert.equal(await p.locator('#pose-road-options').getAttribute('open'),'');
 assert.match(await p.evaluate(()=>document.activeElement.textContent),/external strand · 52.2 mm/);
 assert.equal(await p.locator('#pose-road-buttons [aria-pressed=true]').count(),1);
 await p.locator('#mesh-file').setInputFiles(process.env.FDM_PREVIEW_MESH);await p.waitForFunction(()=>document.querySelector('#mesh-status').textContent.startsWith('Mesh fingerprint matched'));
 const real=JSON.parse(data.get(m.receipts.find(e=>e.pose==='facet-01'&&e.check==='bridge-check').path));
 assert.deepEqual(await p.evaluate(()=>viewer.roadWitness),real.result.metrics.worst.external.strand.design_mm);
 assert.equal(await p.evaluate(()=>draftFormState()),before);
 await p.getByRole('button',{name:'facet-00',exact:true}).click();assert.equal(await p.evaluate(()=>viewer.roadWitness),null);
 await p.locator('#pose-road-buttons').getByRole('button',{name:'internal strand · 122.1 mm',exact:true}).click();
 await p.locator('#pose-road-hide').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>viewer.roadWitness),null);
 assert.match(await p.evaluate(()=>document.activeElement.textContent),/internal strand/);
 await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.locator('#table-file').setInputFiles(path.join(dir,'orientation-table.enriched.json'));
 await p.waitForFunction(()=>document.querySelector('#pose-name').textContent==='Choose a candidate');
 assert.equal(await p.locator('#pose-road-buttons button').count(),0);assert.equal(await p.evaluate(()=>viewer.roadWitness),null);
 await p.getByRole('button',{name:'facet-01',exact:true}).click();assert.equal(await p.locator('#pose-road-buttons button').count(),0);
 assert.equal(await p.locator('[data-locate-failed-bridge]').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS orientation bundle road locations, flipped pose, mesh-load persistence, view-only draft state, pose/table reset and mobile');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
