const {chromium}=require('playwright'),path=require('node:path'),{pathToFileURL}=require('node:url'),fs=require('node:fs/promises'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const tablePath=path.join(__dirname,'../tests/fixtures/orient/spool-rack-g2-ef.orientation-table.json');
 const draftPath=path.join(__dirname,'../tests/fixtures/massing/sample-draft.json'),draft=JSON.parse(await fs.readFile(draftPath,'utf8'));
 const tiny=draft.massing.helper_regions.find(h=>h.name==='Deliberately tiny box');
 page.on('dialog',dialog=>dialog.accept());
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 await page.locator('#review-draft').setInputFiles(draftPath);await page.locator('#review-receipt').setInputFiles(path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json'));
 await page.locator('#review-helpers').getByRole('button',{name:'Edit Deliberately tiny box',exact:true}).click();
 await page.waitForURL('**/index.html#review-edit');assert(await page.locator('#review-transfer').isVisible());
 const raw=await fs.readFile(tablePath);await page.locator('#table-file').setInputFiles({name:'changed-table.json',mimeType:'application/json',buffer:Buffer.concat([raw,Buffer.from(' ')])});
 await page.waitForFunction(()=>document.querySelector('#review-transfer-status').textContent.includes('different orientation table'));
 assert.equal(await page.locator('#pose-name').innerText(),'Choose a candidate');
 await page.locator('#table-file').setInputFiles(tablePath);
 await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.startsWith('Draft restored'));
 assert(await page.locator('#review-transfer').isHidden());
 const target=page.locator('.helper-region').filter({has:page.locator('[data-key="name"]')}).nth(draft.massing.helper_regions.indexOf(tiny));
 assert.equal(await target.locator('[data-key="name"]').inputValue(),tiny.name);
 assert(await target.locator('[data-key="name"]').evaluate(e=>e===document.activeElement));
 const download=page.waitForEvent('download');await page.locator('#export').click();const exported=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));
 assert.deepEqual(exported.massing,draft.massing);assert.equal(exported.source.orientation_table_sha256,draft.source.orientation_table_sha256);
 assert.equal(await page.evaluate(()=>sessionStorage.getItem('fdmgen-review-edit')),null);
 await page.goto('about:blank');await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href+'#review-edit');
 assert.match(await page.locator('#review-transfer-status').innerText(),/manually/);await page.locator('#cancel-review-transfer').click();assert(await page.locator('#review-transfer').isHidden());
 // A real failed clearance check carries its reason, separately from draft intent.
 const originalReport=JSON.parse(await fs.readFile(path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json'),'utf8'));
 const clearance=originalReport.checks.find(c=>c.rule==='KEEP-CLEAR'&&c.verdict==='FAIL');
 const backing=draft.massing.helper_regions.find(h=>h.id===clearance.metrics.helper_id);
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 await page.locator('#review-draft').setInputFiles(draftPath);
 await page.locator('#review-receipt').setInputFiles(path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json'));
 const failedRow=page.locator('#review-checks article').filter({has:page.getByRole('heading',{name:'KEEP-CLEAR · M · FAIL · provisional',exact:true})}).first();
 await failedRow.getByRole('button',{name:'Edit '+backing.name,exact:true}).click();
 await page.waitForURL('**/index.html#review-edit');await page.locator('#table-file').setInputFiles(tablePath);
 await page.waitForFunction(()=>!document.querySelector('#review-edit-context').hidden);
 assert.match(await page.locator('#review-edit-context-summary').innerText(),/13.00 mm/);
 assert.match(await page.locator('#review-edit-context').innerText(),/not a check of your current edits/);
 const context=JSON.parse(await page.locator('#review-edit-context-source').textContent());
 assert.deepEqual(context.check,clearance);
 assert.equal(context.report_sha256,require('node:crypto').createHash('sha256').update(await fs.readFile(path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json'))).digest('hex'));
 const backingFields=page.locator(`.helper-region[data-id="${backing.id}"]`);
 assert(await backingFields.locator('[data-key="name"]').evaluate(e=>e===document.activeElement));
 const snapshot=page.waitForEvent('download');await page.locator('#export').click();
 const unchanged=JSON.parse(await fs.readFile(await(await snapshot).path(),'utf8'));
 assert.deepEqual(unchanged.massing,draft.massing);assert.equal(unchanged.review_context,undefined);
 await backingFields.locator('[data-geometry="center_mm"][data-axis="1"]').fill('-20');
 assert.deepEqual(JSON.parse(await page.locator('#review-edit-context-source').textContent()),context);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#review-edit-context summary').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#dismiss-review-context').focus();await page.keyboard.press('Enter');
 assert(await page.locator('#review-edit-context').isHidden());
 await page.setViewportSize({width:1280,height:720});
 // Synthetic shell-only contract case: no helper exists to carry the edit action.
 const shellDraft=structuredClone(draft);shellDraft.massing.helper_regions=[];shellDraft.massing.shell_only=true;
 const bytes=Buffer.from(JSON.stringify(shellDraft));
 const report=JSON.parse(await fs.readFile(path.join(__dirname,'../tests/fixtures/massing/sample-export-report.json'),'utf8'));
 report.plan.draft_sha256=require('node:crypto').createHash('sha256').update(bytes).digest('hex');report.helpers=[];report.checks=[];
 await page.goto(pathToFileURL(path.join(__dirname,'massing-review.html')).href);
 await page.locator('#review-draft').setInputFiles({name:'shell-only-draft.json',mimeType:'application/json',buffer:bytes});
 await page.locator('#review-receipt').setInputFiles({name:'shell-only-report.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(report))});
 await page.getByRole('button',{name:'Revise this draft',exact:true}).click();await page.waitForURL('**/index.html#review-edit');
 assert.match(await page.locator('#review-transfer-status').innerText(),/shell controls/);
 await page.locator('#table-file').setInputFiles(tablePath);
 await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.startsWith('Draft restored'));
 assert(await page.locator('#shell-only').isChecked());assert.equal(await page.locator('.helper-region').count(),0);
 assert.equal(await page.evaluate(()=>document.activeElement.id),'walls');
 const shellDownload=page.waitForEvent('download');await page.locator('#export').click();
 const shellExport=JSON.parse(await fs.readFile(await(await shellDownload).path(),'utf8'));
 assert.deepEqual(shellExport.massing,shellDraft.massing);assert.equal(shellExport.orientation.id,shellDraft.orientation.id);
 assert.equal(await page.evaluate(()=>sessionStorage.getItem('fdmgen-review-edit')),null);
 assert.deepEqual(errors,[]);console.log('PASS helper and shell-only review handoffs, historical clearance context separate from draft, exact table restore, focus, preserved massing, consumed transfer and fallback');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
